// Generated by scripts/generate-l10n.sh — DO NOT EDIT MANUALLY
import Foundation

// MARK: - L10n

/// CoreUI バンドル内の Localizable.xcstrings からローカライズ文字列を提供する。
///
/// プロパティ名は Xcode が String Catalog から生成するシンボル名規則（ドット除去のキャメルケース）に準拠する。
/// 例: キー `cityList.title` → `L10n.cityListTitle`
///
/// View 側は `Text(L10n.cityListTitle)` のように使用する。
public enum L10n {
    public static var cityListTitle: LocalizedStringResource {
        LocalizedStringResource("cityList.title", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var citySearchEmptyResult: LocalizedStringResource {
        LocalizedStringResource("citySearch.emptyResult", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var citySearchSearchPrompt: LocalizedStringResource {
        LocalizedStringResource("citySearch.searchPrompt", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var citySearchTitle: LocalizedStringResource {
        LocalizedStringResource("citySearch.title", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var currentWeatherFeelsLikePrefix: LocalizedStringResource {
        LocalizedStringResource("currentWeather.feelsLikePrefix", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var currentWeatherHourlyChartButton: LocalizedStringResource {
        LocalizedStringResource("currentWeather.hourlyChartButton", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var currentWeatherLoading: LocalizedStringResource {
        LocalizedStringResource("currentWeather.loading", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var currentWeatherOpenSettings: LocalizedStringResource {
        LocalizedStringResource("currentWeather.openSettings", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var currentWeatherRetry: LocalizedStringResource {
        LocalizedStringResource("currentWeather.retry", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var currentWeatherTitle: LocalizedStringResource {
        LocalizedStringResource("currentWeather.title", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var currentWeatherTodayForecast: LocalizedStringResource {
        LocalizedStringResource("currentWeather.todayForecast", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var currentWeatherWeeklyForecastButton: LocalizedStringResource {
        LocalizedStringResource("currentWeather.weeklyForecastButton", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var hourlyChartPrecipitation: LocalizedStringResource {
        LocalizedStringResource("hourlyChart.precipitation", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var hourlyChartTemperature: LocalizedStringResource {
        LocalizedStringResource("hourlyChart.temperature", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var hourlyChartTime: LocalizedStringResource {
        LocalizedStringResource("hourlyChart.time", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var hourlyChartTitle: LocalizedStringResource {
        LocalizedStringResource("hourlyChart.title", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var settingsAppearanceSection: LocalizedStringResource {
        LocalizedStringResource("settings.appearanceSection", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var settingsInfoSection: LocalizedStringResource {
        LocalizedStringResource("settings.infoSection", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var settingsTemperaturePicker: LocalizedStringResource {
        LocalizedStringResource("settings.temperaturePicker", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var settingsThemePicker: LocalizedStringResource {
        LocalizedStringResource("settings.themePicker", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var settingsTitle: LocalizedStringResource {
        LocalizedStringResource("settings.title", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var settingsUnitSection: LocalizedStringResource {
        LocalizedStringResource("settings.unitSection", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var settingsWindPicker: LocalizedStringResource {
        LocalizedStringResource("settings.windPicker", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var tabCity: LocalizedStringResource {
        LocalizedStringResource("tab.city", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var tabSettings: LocalizedStringResource {
        LocalizedStringResource("tab.settings", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var tabWeather: LocalizedStringResource {
        LocalizedStringResource("tab.weather", bundle: .atURL(Bundle.module.bundleURL))
    }

    public static var weeklyForecastTitle: LocalizedStringResource {
        LocalizedStringResource("weeklyForecast.title", bundle: .atURL(Bundle.module.bundleURL))
    }
}
